KCC-Team/KCC-PMS

src/main/webapp/WEB-INF/views/common.jsp

menu_update

---

src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/project/dashboard.jsp
src/main/webapp/WEB-INF/views/project/info.jsp
src/main/webapp/WEB-INF/views/project/list.jsp
src/main/webapp/WEB-INF/views/project/modify.jsp
src/main/webapp/WEB-INF/views/project/register.jsp
src/main/webapp/resources/project/css/info.css
src/main/webapp/resources/project/css/modify.css
src/main/webapp/resources/project/css/register.css

- 프로젝트 경로 및 UI 수정
- resolved: #10

프로젝트 경로 및 UI 수정

---

.gitignore
src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
src/main/resources/application-secret.yml.template
src/main/resources/application.yml

- yml에 db 정보를 작성했습니다.
- 각 환경 (개발, 테스트, 운영) 별 정보를 다르게 구성할 수 있도록 환경을 분리했습니다.
- secret.yml의 구조를 담은 템플릿을 첨부했습니다.
- db 정보는 각 컴퓨터에 띄워진 oracle 정보로 바꿔주시길 바랍니다.
- resolved: #13

[#13] 프로젝트 yml 구성

---

src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/project/wbsList.jsp
src/main/webapp/resources/common/css/common.css

header layout modify

---

src/main/java/com/kcc/pms/domain/task/danger/controller/DangerController.java
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/danger/danger_list.jsp
src/main/webapp/resources/danger/css/ax5grid.css
src/main/webapp/resources/danger/css/danger.css
src/main/webapp/resources/danger/js/danger.js

위험 목록 UI 구현

---

src/main/webapp/WEB-INF/views/login.jsp

- project/list -> projects/list
- resolved: #19

로그인.jsp form태그 action 재설정_시큐리티적용전

---

src/main/java/com/kcc/pms/domain/task/danger/controller/DangerController.java
src/main/java/com/kcc/pms/domain/task/issue/controller/IssueController.java
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/danger/info.jsp
src/main/webapp/WEB-INF/views/header.jsp
src/main/webapp/WEB-INF/views/issue/info.jsp
src/main/webapp/WEB-INF/views/issue/list.jsp
src/main/webapp/WEB-INF/views/project/wbsList.jsp
src/main/webapp/resources/common/css/common.css
src/main/webapp/resources/danger/css/danger.css
src/main/webapp/resources/danger/js/info.js
src/main/webapp/resources/issue/css/info.css
src/main/webapp/resources/issue/js/info.js
src/main/webapp/resources/issue/js/list.js
src/main/webapp/resources/project/css/dashboard.css
src/main/webapp/resources/project/css/wbsList.css

이슈/위험 UI 작업

---

src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/member/js/list.js

- 투입 인력 관리 UI 작업
- resolved: #22

투입 인력 관리 UI 작업

---

pom.xml
src/main/webapp/WEB-INF/views/output/list.jsp
src/main/webapp/resources/common/css/common.css
src/main/webapp/resources/output/css/list.css
src/main/webapp/resources/output/js/list.js

- jstl 모듈 추가
- ax5 그리드 추
- #15

[#15] 산출물 관리 UI 구현

---

src/main/webapp/WEB-INF/views/output/file-detail-modal.jsp
src/main/webapp/WEB-INF/views/output/list.jsp
src/main/webapp/resources/output/css/ax5grid.css
src/main/webapp/resources/output/css/list.css
src/main/webapp/resources/output/js/list.js

- 산출물 파일 상세 조회 로직을 구현 중입니다.
- #28

[#28] 산출물 파일 상세 조회 로직 구현

---

src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/WEB-INF/views/member/memberRegister.jsp
src/main/webapp/resources/member/css/ax5grid.css
src/main/webapp/resources/member/css/memberRegister.css
src/main/webapp/resources/member/js/list.js
src/main/webapp/resources/member/js/memberRegister.js
src/main/webapp/resources/member/js/memberRegisterGrid.js

- 인력 등록 팝업 화면 구현
- 조직도 및 프로젝트 인원 목록으로부터 인원 추가
- resolved: #8

feat: 인력등록팝업화면구현(8)

---

src/main/webapp/resources/member/js/memberRegisterGrid.js

- 인력 등록 시 권한목록을 공통코드로부터 가져옵니다.
- resolved: #39

[#39] 권한목록 조회 서버,화면 로직 구현

---

src/main/java/com/kcc/pms/domain/common/model/dto/CommonCodeSelectListResponseDto.java
src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
src/main/java/com/kcc/pms/domain/member/model/dto/GroupResponseDto.java
src/main/java/com/kcc/pms/domain/member/service/MemberService.java
src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/resources/member/js/memberRegister.js

-조직도 트리구조로 조회, 서버로직 구현
- resolved: #41

[#41] 트리구조로 조직도 조회 서버 로직 구현

---

src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/member/js/list.js

- 인력관리 화면 UI 개선
- resolved: #46

[#46] 인력관리 화면 UI 개선

---

src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
src/main/java/com/kcc/pms/domain/project/model/dto/ProjectManagerResponseDto.java
src/main/java/com/kcc/pms/domain/project/model/dto/ProjectRequestDto.java
src/main/java/com/kcc/pms/domain/project/model/dto/ProjectResponseDto.java
src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
src/main/resources/mapper/ProjectMapper.xml
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/project/dashboard.jsp
src/main/webapp/WEB-INF/views/project/list.jsp
src/main/webapp/resources/member/js/memberRegisterGrid.js

- 프로젝트 전체 목록 조회 작업
- 권한 있는 프로젝트만 조회 가능
- PM 등록은 1명만 가능

#[51] 프로젝트 조회 작업

---

src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
src/main/java/com/kcc/pms/domain/project/model/dto/CombinedProjectResponseDto.java
src/main/java/com/kcc/pms/domain/project/model/dto/ProjectRequestDto.java
src/main/java/com/kcc/pms/domain/project/model/dto/ProjectResponseDto.java
src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
src/main/resources/mapper/ProjectMapper.xml
src/main/webapp/WEB-INF/views/header.jsp
src/main/webapp/WEB-INF/views/project/dashboard.jsp
src/main/webapp/WEB-INF/views/project/info.jsp
src/main/webapp/WEB-INF/views/project/list.jsp
src/main/webapp/resources/common/js/common.js
src/main/webapp/resources/project/css/info.css
src/main/webapp/resources/project/css/list.css
src/main/webapp/resources/project/css/register.css
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/project/js/list.js

- 프로젝트 상세 정보 조회 구현
- 프로젝트 수정 구현
- dashboard 연결
- 공통 헤더 프로젝트 변경시 세션으로 데이터 변경 구현
- 프로젝트 진입 시 세션 생성 (prjNo, prjTitle)
- 프로젝트 변경 시 세션 변경
- resolved: #58

[#58] 프로젝트 수정 구현

---

src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/member/js/list.js

-  팀 생성 화면 구현 
- resolved: #64

[#64] 팀 생성 화면 구현 

---

src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/member/js/list.js

-  팀 등록 디자인 변경 
- resolved: #72

[#72] 팀 등록 디자인 변경 

---

src/main/webapp/WEB-INF/views/danger/danger_list.jsp
src/main/webapp/WEB-INF/views/danger/info.jsp
src/main/webapp/WEB-INF/views/issue/info.jsp
src/main/webapp/WEB-INF/views/issue/list.jsp
src/main/webapp/resources/danger/css/ax5grid.css
src/main/webapp/resources/danger/js/danger.js
src/main/webapp/resources/danger/js/info.js
src/main/webapp/resources/issue/css/info.css
src/main/webapp/resources/issue/js/info.js
src/main/webapp/resources/issue/js/list.js
src/main/webapp/resources/project/css/info.css
src/main/webapp/resources/project/css/register.css

- 이슈 / 위험 / 프로젝트 레이아웃 수정
- resolved: #70

[#70] 이슈 / 위험 / 프로젝트 레이아웃 수정

---

pom.xml
src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
src/main/java/com/kcc/pms/domain/test/controller/TestController.java
src/main/java/com/kcc/pms/domain/test/domain/dto/TestListResponseDto.java
src/main/java/com/kcc/pms/domain/test/mapper/TestMapper.java
src/main/java/com/kcc/pms/domain/test/service/TestService.java
src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
src/main/resources/data.sql
src/main/resources/mapper/TestMapper.xml
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/defect/list.jsp
src/main/webapp/WEB-INF/views/output/list.jsp
src/main/webapp/WEB-INF/views/test/list.jsp
src/main/webapp/resources/test/css/list.css
src/main/webapp/resources/test/js/list.js

- 테스트 기본 경로 및 기타 경로 변경
- 테스트 조회 로직을 구현했습니다.
- 기본 더미데이터 sql을 추가했습니다.
- 아직 로직이 마무리 되지 않았습니다. 참고해주세요
- #61

[#61] 테스트 목록 API 구현 중간 적용 및 설정 적용

---

src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
src/main/java/com/kcc/pms/domain/system/controller/SystemController.java
src/main/java/com/kcc/pms/domain/system/mapper/SystemMapper.java
src/main/java/com/kcc/pms/domain/system/model/dto/SystemResponseDTO.java
src/main/java/com/kcc/pms/domain/system/service/SystemService.java
src/main/java/com/kcc/pms/domain/system/service/SystemServiceImpl.java
src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
src/main/java/com/kcc/pms/domain/team/mapper/TeamMapper.java
src/main/java/com/kcc/pms/domain/team/model/dto/TeamRequestDto.java
src/main/java/com/kcc/pms/domain/team/model/vo/Team.java
src/main/java/com/kcc/pms/domain/team/service/TeamService.java
src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
src/main/resources/mapper/SystemMapper.xml
src/main/resources/mapper/TeamMapper.xml
src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/member/js/list.js

- 팀 생성 서버 로직 구현
- resolved: #65

[#65] 팀 생성 서버 로직 구현

---

src/main/java/com/kcc/pms/domain/project/controller/WbsController.java
src/main/resources/data.sql
src/main/resources/mapper/ProjectMapper.xml
src/main/webapp/WEB-INF/views/header.jsp
src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
src/main/webapp/WEB-INF/views/wbs/wbsList.jsp
src/main/webapp/resources/danger/js/danger.js
src/main/webapp/resources/issue/js/list.js
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/wbs/css/wbsInfo.css
src/main/webapp/resources/wbs/css/wbsList.css
src/main/webapp/resources/wbs/js/wbsList.js

- 프로젝트, WBS, 이슈, 위험 레이아웃 수정
- resolved: #69

[#69] 프로젝트, WBS, 이슈, 위험 레이아웃 수정

---

src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
src/main/java/com/kcc/pms/domain/member/model/dto/ProjectMemberResponseDto.java
src/main/java/com/kcc/pms/domain/member/service/MemberService.java
src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
src/main/resources/application.yml
src/main/resources/mapper/MemberMapper.xml
src/main/resources/mapper/TeamMapper.xml
src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/member/js/list.js

- 사원 팀 배정 드래그 앤 드롭 구현
- 배정된 결과에 따라 팀 인원수 변경
- resolved: #77

[#77] 사원 팀 배정 드래그 앤 드롭 구현

---

src/main/resources/mapper/ProjectMapper.xml
src/main/webapp/WEB-INF/views/member/memberRegister.jsp
src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
src/main/webapp/resources/member/js/memberRegisterGrid.js
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/wbs/css/wbsInfo.css
src/main/webapp/resources/wbs/js/wbsInfo.js
src/main/webapp/resources/wbs/js/wbsList.js

- 프로젝트 WBS 레이아웃 구현
- resolved: #80

[#80] 프로젝트 WBS 레이아웃 구현

---

src/main/resources/application.yml
src/main/resources/data.sql
src/main/resources/mapper/ProjectMapper.xml

- 프로젝트 update 쿼리 수정 / 더미 데이터 추가

[#85] 프로젝트 update 수정

---

src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
src/main/java/com/kcc/pms/domain/member/service/MemberService.java
src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/member/memberRegister.jsp
src/main/webapp/resources/member/js/list.js
src/main/webapp/resources/member/js/memberRegisterGrid.js

- api경로 수정
- 인력/프로젝트 병합
- resolved: #87

[#87] api경로 수정 및  인력,프로젝트 병합, 무소속 팀원 처리

---

src/main/resources/data.sql

- 각 컴퓨터의 있는 더미데이터를 통합했습니다.
- resolved: #

[#noissue] 더미데이터 최신화

---

src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
src/main/java/com/kcc/pms/domain/wbs/service/WbsServiceImpl.java
src/main/resources/mapper/ProjectMapper.xml
src/main/webapp/WEB-INF/views/header.jsp
src/main/webapp/resources/common/js/common.js
src/main/webapp/resources/member/js/memberRegisterGrid.js
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/wbs/js/wbsInfo.js
src/main/webapp/resources/wbs/js/wbsList.js

- 프로젝트명 세션 수정
- 프로젝트 팀원 목록 수정
- resolved: #91

[#91] 프로젝트명 세션 수정, 프로젝트 팀원 목록 수정

---

src/main/webapp/WEB-INF/views/project/dashboard.jsp
src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/project/css/dashboard.css
src/main/webapp/resources/wbs/js/wbsInfo.js
src/main/webapp/resources/wbs/js/wbsList.js

- ]프로젝트 WBS 등록 구현 / 하위 작업 구현
- resolved: #99

[#99]프로젝트 WBS 등록 구현 / 하위 작업 구현

---

src/main/webapp/WEB-INF/views/danger/danger_list.jsp
src/main/webapp/WEB-INF/views/issue/list.jsp
src/main/webapp/resources/danger/js/danger.js
src/main/webapp/resources/issue/js/list.js

- 위험 이슈 레이아웃 재설정
- resolved: #109

[#109] 위험 이슈 레이아웃 재설정

---

src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
src/main/webapp/WEB-INF/views/defect/list.jsp
src/main/webapp/resources/common/css/common.css
src/main/webapp/resources/danger/css/danger.css
src/main/webapp/resources/defect/js/list.js

- 결함의 레이아웃을 수정했습니다.
- danger에서 사용하던 css를 공통적으로 사용하게 되어 위치를 변경하였습니다.
- 확인하시고 문제가 발생할 것 같으면 코멘트를 남겨주시면 감사하겠습니다. 수정하겠습니다.
- resolved: #106

[#106] 결함 레이아웃 수정

---

src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/member/js/list.js

- 투입인력 페이지 레이아웃 재설정 
- resolved: #113

[#113] 투입인력 페이지 레이아웃 재설정 

---

src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
src/main/webapp/WEB-INF/views/feature/list.jsp
src/main/webapp/resources/feature/css/featureInfo.css
src/main/webapp/resources/feature/js/list.js

- 기능 등록 UI 팝업 페이지 구현
- resolved: #108

[#108] 기능 등록 UI 구현 

---

src/main/java/com/kcc/pms/domain/wbs/controller/WbsController.java
src/main/java/com/kcc/pms/domain/wbs/mapper/WbsMapper.java
src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsOrderUpdateRequestDto.java
src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsRequestDto.java
src/main/java/com/kcc/pms/domain/wbs/model/vo/Wbs.java
src/main/java/com/kcc/pms/domain/wbs/service/WbsService.java
src/main/java/com/kcc/pms/domain/wbs/service/WbsServiceImpl.java
src/main/resources/mapper/WbsMapper.xml
src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
src/main/webapp/resources/wbs/js/wbsInfo.js
src/main/webapp/resources/wbs/js/wbsList.js

- WBS순서변경 서버로직 구현
- resolved: #123

[#123] WBS순서변경 서버로직 구현

---

src/main/java/com/kcc/pms/domain/test/controller/TestController.java
src/main/java/com/kcc/pms/domain/test/domain/dto/TestRequestDto.java
src/main/java/com/kcc/pms/domain/test/domain/vo/TestVO.java
src/main/java/com/kcc/pms/domain/test/mapper/TestMapper.java
src/main/java/com/kcc/pms/domain/test/service/TestService.java
src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
src/main/resources/mapper/TestMapper.xml
src/main/webapp/WEB-INF/views/defect/defect.jsp
src/main/webapp/WEB-INF/views/defect/list.jsp
src/main/webapp/WEB-INF/views/output/file/file-task.jsp
src/main/webapp/WEB-INF/views/output/file/file.jsp
src/main/webapp/WEB-INF/views/output/modal/file-history-modal.jsp
src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
src/main/webapp/WEB-INF/views/output/modal/folder-modal.jsp
src/main/webapp/WEB-INF/views/output/modal/output-file-insert.jsp
src/main/webapp/WEB-INF/views/test/list.jsp
src/main/webapp/resources/common/css/common.css
src/main/webapp/resources/defect/css/defect.css
src/main/webapp/resources/defect/js/defect.js
src/main/webapp/resources/defect/js/list.js
src/main/webapp/resources/output/js/list.js
src/main/webapp/resources/test/css/list.css
src/main/webapp/resources/test/js/list.js

- 결함 정보의 레이아웃을 수정했습니다.
- 파일 업로드 구조를 분리했습니다.

[#120] 결함, 산출물 파일 레이아웃 분리 및 개선

---

pom.xml
src/main/java/com/kcc/pms/domain/common/config/AwsS3Config.java
src/main/java/com/kcc/pms/domain/common/config/EnvVariableProperties.java
src/main/java/com/kcc/pms/domain/common/config/ProperTiesConfig.java
src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
src/main/java/com/kcc/pms/domain/common/service/CommonService.java
src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
src/main/java/com/kcc/pms/domain/common/util/AwsS3Utils.java
src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
src/main/java/com/kcc/pms/domain/output/domain/dto/FileStructResponseDto.java
src/main/java/com/kcc/pms/domain/output/domain/vo/FileMasterVO.java
src/main/java/com/kcc/pms/domain/output/mapper/FileMapper.java
src/main/java/com/kcc/pms/domain/output/mapper/OutputMapper.java
src/main/resources/application.yml
src/main/resources/data.sql
src/main/resources/mapper/FileMapper.xml
src/main/webapp/WEB-INF/views/output/file/file.jsp
src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
src/main/webapp/WEB-INF/views/output/modal/folder-modal.jsp
src/main/webapp/resources/output/js/jstree.js

- 파일 업로드 로직을 구현했습니다.
- 업로드 서버 로직만 구현 되었을 뿐 아직 DropZone과 연결되지 않았습니다,
- 이후에 더 작업을 진행하도록 하겠습니다.
- #128

[#128] 파일 업로드 API 구현

---

src/main/webapp/WEB-INF/views/member/memberRegister.jsp
src/main/webapp/resources/feature/css/featureInfo.css
src/main/webapp/resources/feature/js/list.js
src/main/webapp/resources/member/css/memberRegister.css
src/main/webapp/resources/member/js/memberRegisterGrid.js
src/main/webapp/resources/wbs/css/wbsInfo.css
src/main/webapp/resources/wbs/js/wbsList.js

-  WBS정보, 기능정보 팝업 레이아웃 수정
- 인력 버튼 수정
- resolved: #131

[#131] WBS정보, 기능정보 팝업 레이아웃 수정 

---

src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
src/main/java/com/kcc/pms/domain/team/mapper/TeamMapper.java
src/main/java/com/kcc/pms/domain/team/model/dto/TeamResponseDto.java
src/main/java/com/kcc/pms/domain/team/model/dto/TeamTreeResponseDto.java
src/main/java/com/kcc/pms/domain/team/model/dto/TreeNode.java
src/main/java/com/kcc/pms/domain/team/service/TeamService.java
src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
src/main/resources/mapper/TeamMapper.xml
src/main/webapp/WEB-INF/views/member/teamMemberRegister.jsp
src/main/webapp/resources/member/js/teamMemberRegister.js

[#132] 팀 트리 생성 

---

src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
src/main/java/com/kcc/pms/domain/member/model/dto/ProjectMemberResponseDto.java
src/main/java/com/kcc/pms/domain/member/service/MemberService.java
src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
src/main/java/com/kcc/pms/domain/team/model/dto/TeamMemberResponseDto.java
src/main/java/com/kcc/pms/domain/team/service/TeamService.java
src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
src/main/resources/application.yml
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/WEB-INF/views/member/teamMemberRegister.jsp
src/main/webapp/resources/member/css/memberRegister.css
src/main/webapp/resources/member/js/list.js
src/main/webapp/resources/member/js/teamMemberRegister.js
src/main/webapp/resources/member/js/teamMemberRegisterGrid.js

- 팀 트리 구조 인력 선택 팝업 페이지 구현
application.yml db설정 확인부탁드립니다
- resolved: #121

[#121] 팀 트리 구조 인력 선택 팝업

---

src/main/webapp/WEB-INF/views/member/teamMemberRegister.jsp
src/main/webapp/resources/common/js/common.js
src/main/webapp/resources/member/css/memberRegister.css
src/main/webapp/resources/member/css/teamMemberRegister.css
src/main/webapp/resources/member/js/list.js
src/main/webapp/resources/member/js/teamMemberRegisterGrid.js

- 작업자 등록 팝업 페이지 common.js 이동
- 레이아웃 변경
- resolved: #137

[#137]  팀 트리 구조 인력 등록 팝업 수정 

---

src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/java/com/kcc/pms/domain/wbs/controller/WbsController.java
src/main/java/com/kcc/pms/domain/wbs/mapper/WbsMapper.java
src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsResponseDto.java
src/main/java/com/kcc/pms/domain/wbs/service/WbsService.java
src/main/java/com/kcc/pms/domain/wbs/service/WbsServiceImpl.java
src/main/resources/data.sql
src/main/resources/mapper/WbsMapper.xml
src/main/webapp/WEB-INF/views/danger/info.jsp
src/main/webapp/WEB-INF/views/issue/info.jsp
src/main/webapp/WEB-INF/views/member/memberRegister.jsp
src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
src/main/webapp/resources/danger/css/danger.css
src/main/webapp/resources/danger/js/info.js
src/main/webapp/resources/issue/css/info.css
src/main/webapp/resources/member/js/memberRegisterGrid.js
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/wbs/css/wbsInfo.css
src/main/webapp/resources/wbs/css/wbsList.css
src/main/webapp/resources/wbs/js/wbsInfo.js
src/main/webapp/resources/wbs/js/wbsList.js

- 이슈 / 위험 레이아웃 수정
- 프로젝트 WBS 수정 / 상세 구현
- resolved: #130

[#130] 이슈 / 위험 레이아웃 수정 , 프로젝트 WBS 수정 / 상세 구현

---

src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
src/main/webapp/resources/feature/css/featureInfo.css
src/main/webapp/resources/feature/js/featureInfo.js
src/main/webapp/resources/feature/js/list.js

- 기능 등록 팝업 페이지 시스템/업무 선택박스 추가
- 시스템/업무명이 길어질시 줄임말 적용
- resolved: #145

[#145] 기능 등록 팝업 페이지 시스템/업무 선택박스 추가 및 줄임말 적용

---

src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
src/main/resources/mapper/ProjectMapper.xml

- 로그인 시 최근 프로젝트 update 구현
- resolved: #151

[#151] 최근 프로젝트 update 구현

---

src/main/webapp/WEB-INF/views/feature/list.jsp
src/main/webapp/resources/feature/css/featureList.css
src/main/webapp/resources/feature/js/list.js

- 기능 목록 레이아웃 구현
- resolved: #153

[#153] 기능 목록 레이아웃 구현

---

src/main/resources/application.yml
src/main/webapp/WEB-INF/views/feature/list.jsp
src/main/webapp/resources/feature/css/featureList.css
src/main/webapp/resources/feature/js/list.js

- 기능페이지 전체 진척률 도넛차트 추가
- 기능페이지 개발자진척률 그리드 추가
- 기능페이지 지연목록 그리드 추가
- 
- resolved: #156

[#156] 기능페이지 전체 진척률 도넛차트, 개발자진척률, 지연목록 그리드 추가

---

src/main/java/com/kcc/pms/auth/SecurityConfig.java
src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
src/main/java/com/kcc/pms/domain/project/model/dto/RecentProjectDto.java
src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
src/main/resources/mapper/ProjectMapper.xml
src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
src/main/webapp/resources/project/js/list.js
src/main/webapp/resources/wbs/css/wbsInfo.css
src/main/webapp/resources/wbs/js/wbsInfo.js
src/main/webapp/resources/wbs/js/wbsList.js

- 로그인 후 프로젝트 선택 시 최근 프로젝트 update
- header 부분 프로젝트 변경 시 최근 프로젝트 update
- WBS 진척률 평균과 프로젝트 진척률 연결 작업
- WBS 등록/수정 시 시스템 연결
- resolved: #155

[#155] 로그인 시 대시 보드 연결 및 WBS 진척률과 프로젝트 진척률 연결 작업

---

src/main/resources/application.yml

[#noissue] 서버 로깅 레벨 변경

---

src/main/resources/application.yml

[#noissue] sql 초기화 수정

---

src/main/resources/application.yml

[#noissue] 서버 환경 분리

---

Dockerfile
pom.xml
src/main/java/com/kcc/pms/PmsApplication.java
src/main/resources/application.yml

[#noissue] 배포 방식 war로 변경

---

src/main/java/com/kcc/pms/auth/SecurityConfig.java
src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
src/main/java/com/kcc/pms/init/init.java
src/main/resources/application.yml
src/main/resources/data.sql
src/main/webapp/WEB-INF/views/header.jsp
src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/wbs/css/wbsInfo.css
src/main/webapp/resources/wbs/js/wbsInfo.js

- WBS 인원등록 팝업 변경
- header.jsp  -> authcode 공통 변수 생성
- pm만 프로젝트 수정 가능
- member 더미 데이터 변경
- 로그인 시 최근 프로젝트 확인 후 연결
- resolved: #163

[#163] WBS 인원등록 팝업 변경 권한 코드 공통 변수 생성

---

Dockerfile
pom.xml
src/main/java/com/kcc/pms/PmsApplication.java
src/main/java/com/kcc/pms/auth/SecurityConfig.java
src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureProgressResponseDto.java
src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureSummaryResponseDto.java
src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
src/main/java/com/kcc/pms/domain/feature/service/FeatureServiceImpl.java
src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
src/main/java/com/kcc/pms/init/init.java
src/main/resources/application.yml
src/main/resources/data.sql
src/main/resources/mapper/FeatureMapper.xml
src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
src/main/webapp/WEB-INF/views/feature/list.jsp
src/main/webapp/WEB-INF/views/header.jsp
src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/resources/feature/css/featureList.css
src/main/webapp/resources/feature/js/featureInfo.js
src/main/webapp/resources/feature/js/list.js
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/wbs/css/wbsInfo.css
src/main/webapp/resources/wbs/js/wbsInfo.js

작업 사항 운영 서버 배포

---

src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
src/main/resources/application.yml
src/main/resources/mapper/ProjectMapper.xml
src/main/webapp/WEB-INF/views/project/dashboard.jsp
src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
src/main/webapp/resources/feature/css/featureList.css
src/main/webapp/resources/project/css/dashboard.css
src/main/webapp/resources/project/js/dashboard.js
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/wbs/js/wbsInfo.js

- 대시보드(이슈, 위험 추후 작업 예정)
- 기능 레이아웃 수정
- 프로젝트, WBS 날짜 체크 추가
- resolved: #179

[#179] 대시보드 구현

---

src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/member/js/list.js

- 팀트리 열린구조 유지 
- resolved: #184

[#184] 팀트리 열린구조 유지 

---

src/main/resources/data.sql
src/main/resources/mapper/ProjectMapper.xml
src/main/webapp/resources/project/css/list.css
src/main/webapp/resources/wbs/css/wbsList.css
src/main/webapp/resources/wbs/js/wbsList.js

- 프로젝트 PM 다중 조회 수정
- 프로젝트 더미 데이터 추가
- WBS 더미 데이터 추가
- resolved: #191

[#191] 프로젝트 PM 조회 수정 및 더미 데이터 추가

---

src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureCreateRequestDto.java
src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureDetailResponseDto.java
src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
src/main/java/com/kcc/pms/domain/feature/service/FeatureServiceImpl.java
src/main/resources/mapper/FeatureMapper.xml
src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
src/main/webapp/resources/feature/js/featureInfo.js
src/main/webapp/resources/feature/js/list.js

- 기능 상세 조회
- 기능 수정
- resolved: #189

[#189] 기능 상세 조회 및 수정 

---

src/main/webapp/WEB-INF/views/project/list.jsp
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/wbs/css/wbsList.css
src/main/webapp/resources/wbs/js/wbsList.js

- 프로젝트 진척률 수정
- WBS 높이 수정
- resolved: #193

[#193] 프로젝트 진척률 수정 및 WBS 높이 수정

---

src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectDto.java
src/main/java/com/kcc/pms/domain/task/defect/mapper/DefectMapper.java
src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
src/main/resources/data.sql
src/main/resources/mapper/task/DefectMapper.xml
src/main/webapp/WEB-INF/views/defect/defect.jsp
src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
src/main/webapp/resources/defect/css/defect.css
src/main/webapp/resources/defect/js/defect.js
src/main/webapp/resources/defect/js/list.js

- 결함 부분의 조치 첨부파일 미적용 부분을 개선했습니다.
- 파일 저장 시에 UUID가 단일 값으로 적용되는 문제를 개선했습니다.
- resolved: #200

[#200] 결함 로직 개선 및 파일명 UUID 미적용 개선

---

src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
src/main/java/com/kcc/pms/domain/feature/model/dto/CriteriaY.java
src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureCreateRequestDto.java
src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureDetailResponseDto.java
src/main/java/com/kcc/pms/domain/feature/model/dto/PageYDto.java
src/main/java/com/kcc/pms/domain/feature/model/dto/PagedResponse.java
src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
src/main/java/com/kcc/pms/domain/feature/service/FeatureServiceImpl.java
src/main/resources/mapper/FeatureMapper.xml
src/main/webapp/WEB-INF/views/feature/list.jsp
src/main/webapp/resources/feature/css/featureList.css
src/main/webapp/resources/feature/js/featureInfo.js
src/main/webapp/resources/feature/js/list.js

- 기능관리 검색 및 페이징 구현
- 시스템 미선택 상황 개선
- 기능등록 시 페이지 새로고침 로직 삭제
- 기능등록 시 해당 내용 관련 reload
- resolved: #195

[#195] 기능관리 검색 및 페이징 구현 & 기능등록 시 해당 내용으로 reload

---

src/main/java/com/kcc/pms/domain/wbs/controller/WbsController.java
src/main/java/com/kcc/pms/domain/wbs/mapper/WbsMapper.java
src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsRequestDto.java
src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsResponseDto.java
src/main/java/com/kcc/pms/domain/wbs/service/WbsService.java
src/main/java/com/kcc/pms/domain/wbs/service/WbsServiceImpl.java
src/main/resources/mapper/WbsMapper.xml
src/main/webapp/WEB-INF/views/output/output-search.jsp
src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
src/main/webapp/resources/member/js/teamMemberRegister.js
src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
src/main/webapp/resources/wbs/css/wbsInfo.css
src/main/webapp/resources/wbs/js/wbsInfo.js

- WBS와 산출물 팝업 연결 작업
- WBS 인원 등록 팝업 오픈 시 트리 전체 오픈되도록 수정
- resolved: #202

[#202] WBS와 산출물 연결 작업

---

src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectDto.java
src/main/java/com/kcc/pms/domain/task/defect/mapper/DefectMapper.java
src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
src/main/resources/data.sql
src/main/resources/mapper/task/DefectMapper.xml
src/main/webapp/WEB-INF/views/defect/defect.jsp
src/main/webapp/WEB-INF/views/defect/list.jsp
src/main/webapp/WEB-INF/views/test/list.jsp
src/main/webapp/resources/defect/js/defect.js
src/main/webapp/resources/defect/js/list.js
src/main/webapp/resources/member/js/teamMemberRegister.js
src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
src/main/webapp/resources/output/js/jstree.js
src/main/webapp/resources/output/js/list.js
src/main/webapp/resources/test/js/list.js

- 사용자 공통 코드를 불러오는 로직을 개선했습니다
- 결함의 사용자 등록을 사용자 선택 모듈을 사용하는 것으로 개선했습니다.
- resolved: #209

[#209] 결함 공통 코드 로직 개선 & 사용자 선택 기능추가

---

src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/java/com/kcc/pms/domain/system/controller/SystemController.java
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/project/dashboard.jsp
src/main/webapp/WEB-INF/views/system/list.jsp
src/main/webapp/resources/project/js/dashboard.js
src/main/webapp/resources/project/js/info.js
src/main/webapp/resources/system/css/list.css
src/main/webapp/resources/system/js/list.js

- 대시보드 수정
- 시스템 레이아웃 작업
- resolved: #208

[#208] 대시보드 수정 및 시스템 레이아웃 작업

---

src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
src/main/resources/application.yml
src/main/resources/mapper/FeatureMapper.xml
src/main/webapp/WEB-INF/views/feature/list.jsp
src/main/webapp/resources/feature/css/featureList.css
src/main/webapp/resources/feature/js/featureInfo.js
src/main/webapp/resources/feature/js/list.js
src/main/webapp/resources/wbs/js/wbsInfo.js

[#214] 충돌 해결

---

src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
src/main/java/com/kcc/pms/domain/risk/model/dto/RiskDto.java
src/main/java/com/kcc/pms/domain/risk/model/dto/RiskFileRequestDto.java
src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
src/main/java/com/kcc/pms/domain/task/danger/controller/DangerController.java
src/main/resources/mapper/task/RiskMapper.xml
src/main/webapp/WEB-INF/views/danger/info.jsp
src/main/webapp/resources/danger/js/danger.js
src/main/webapp/resources/danger/js/info.js
src/main/webapp/resources/issue/css/info.css

- 위험 생성 및 수정
- 위험 생성 및 수정시 해당 위험 상세로 리다이렉트
- 발견첨부 및 조치첨부 이상X
- resolved: #206

[#206] 위험 생성 및 수정 

---

src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
src/main/java/com/kcc/pms/domain/test/controller/TestController.java
src/main/java/com/kcc/pms/domain/test/domain/dto/TestDto.java
src/main/java/com/kcc/pms/domain/test/domain/dto/TestPageResponseDto.java
src/main/java/com/kcc/pms/domain/test/mapper/TestMapper.java
src/main/java/com/kcc/pms/domain/test/service/TestService.java
src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
src/main/resources/data.sql
src/main/resources/mapper/TestMapper.xml
src/main/resources/mapper/task/DefectMapper.xml
src/main/webapp/WEB-INF/views/defect/defect.jsp
src/main/webapp/WEB-INF/views/defect/list.jsp
src/main/webapp/WEB-INF/views/test/list.jsp
src/main/webapp/WEB-INF/views/test/test.jsp
src/main/webapp/resources/defect/js/defect.js
src/main/webapp/resources/defect/js/list.js
src/main/webapp/resources/member/js/list.js
src/main/webapp/resources/member/js/memberRegisterGrid.js
src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
src/main/webapp/resources/test/css/list.css
src/main/webapp/resources/test/css/test.css
src/main/webapp/resources/test/js/list.js
src/main/webapp/resources/test/js/test.js

- 코드 상에 정적으로 작성되어있던 url 경로를 제거했습니다.
- resolved: #218

[#218] 코드 기본 경로 제거 및 운영환경 유연화

---

src/main/resources/application.yml

현 상황 코드 운영 환경에 배포 적용

---

src/main/java/com/kcc/pms/auth/SecurityConfig.java
src/main/webapp/WEB-INF/views/system/list.jsp
src/main/webapp/resources/system/css/list.css
src/main/webapp/resources/system/js/list.js
src/main/webapp/resources/wbs/css/wbsList.css
src/main/webapp/resources/wbs/js/wbsList.js

- 로그아웃 시 모든 세션 삭제 추가
- wbs 테이블 헤더 폰트 색상 변경
- wbs 차트 색상 변경
- 순서변경 / 간트 차트 크게 보기 버튼 색상 변경
- 작업명 크기 수정
- 시스템 레이아웃 수정
- resolved: #213

[#213] WBS 및 시스템 레이아웃 수정

---

src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
src/main/java/com/kcc/pms/domain/risk/model/dto/CriteriaRisk.java
src/main/java/com/kcc/pms/domain/risk/model/dto/PageRiskDto.java
src/main/java/com/kcc/pms/domain/risk/model/dto/PagedRiskResponse.java
src/main/java/com/kcc/pms/domain/risk/model/dto/RiskSummaryResponseDto.java
src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
src/main/resources/application.yml
src/main/resources/mapper/FeatureMapper.xml
src/main/resources/mapper/task/RiskMapper.xml
src/main/webapp/WEB-INF/views/danger/danger_list.jsp
src/main/webapp/resources/danger/css/danger.css
src/main/webapp/resources/danger/js/danger.js

- 위험 목록 검색 및 필터링 조회
- 그리드 크기 축소
- resolved: #217

feat: 위험 목록 검색 및 필터링 조회 + 그리드 크기 축소 (#217)

---

src/main/resources/data.sql

-  위험 더미데이터 추가
- resolved: #225

[#225] 위험 더미데이터 추가

---

src/main/webapp/WEB-INF/views/danger/danger_list.jsp
src/main/webapp/WEB-INF/views/danger/info.jsp
src/main/webapp/WEB-INF/views/issue/info.jsp
src/main/webapp/WEB-INF/views/issue/list.jsp
src/main/webapp/resources/danger/css/danger.css
src/main/webapp/resources/issue/css/info.css
src/main/webapp/resources/issue/js/info.js

- 이슈 / 위험 레이아웃 수정
- resolved: #223

[#223] 이슈 / 위험 레이아웃 수정

---

src/main/java/com/kcc/pms/domain/common/config/EnvVariableProperties.java
src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
src/main/java/com/kcc/pms/domain/common/mapper/CommonMapper.java
src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
src/main/java/com/kcc/pms/domain/common/util/AwsS3Utils.java
src/main/java/com/kcc/pms/domain/output/mapper/FileMapper.java
src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
src/main/resources/application.yml
src/main/resources/data.sql
src/main/resources/mapper/common/FileMapper.xml
src/main/resources/mapper/task/DefectMapper.xml
src/main/webapp/WEB-INF/views/common.jsp
src/main/webapp/WEB-INF/views/defect/defect.jsp
src/main/webapp/WEB-INF/views/defect/list.jsp
src/main/webapp/WEB-INF/views/output/file/file-task.jsp
src/main/webapp/WEB-INF/views/output/file/file.jsp
src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
src/main/webapp/WEB-INF/views/test/test.jsp
src/main/webapp/resources/defect/css/defect.css
src/main/webapp/resources/defect/css/list.css
src/main/webapp/resources/defect/js/defect.js
src/main/webapp/resources/defect/js/list.js
src/main/webapp/resources/member/js/teamMemberRegister.js
src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
src/main/webapp/resources/output/js/list.js
src/main/webapp/resources/test/css/test.css
src/main/webapp/resources/test/js/test.js

- 삭제 시 alert 과정 추가
- 파일 클릭 시 다운로드
- 구조 변경
아직 검증 처리는 되지 않았습니다. 이후에 진행하겠습니다.
- resolved: #234

[#234] 결함 도메인 개선사항 적용

---

src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
src/main/java/com/kcc/pms/domain/risk/model/dto/RiskFileRequestDto.java
src/main/java/com/kcc/pms/domain/risk/model/dto/RiskHistoryDto.java
src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
src/main/resources/mapper/task/RiskMapper.xml
src/main/webapp/WEB-INF/views/danger/info.jsp
src/main/webapp/resources/danger/js/info.js
src/main/webapp/resources/issue/css/info.css

- 위험 조치이력 생성 및 수정
- 조치이력 등록 시 첨부파일 함께 등록
- resolved: #231

[#231] 위험 조치이력 생성 및 수정

---

src/main/resources/data.sql
src/main/webapp/resources/danger/js/info.js

- 썸네일 이미지 조회
- 문서 다운로드
- resolved: #239

[#239] 위험첨부오류해결

---

src/main/resources/data.sql
src/main/webapp/WEB-INF/views/danger/info.jsp
src/main/webapp/resources/danger/js/info.js
src/main/webapp/resources/issue/css/info.css

- 위험상세 레이아웃 수정
- 조치이력 스크롤 반영
- resolved: #241

[#241] 위험상세 레이아웃 수정 및 조치이력 스크롤 반영

---

src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
src/main/resources/data.sql
src/main/resources/mapper/task/RiskMapper.xml
src/main/webapp/WEB-INF/views/danger/info.jsp
src/main/webapp/WEB-INF/views/header.jsp
src/main/webapp/resources/danger/js/info.js
src/main/webapp/resources/issue/css/info.css

- 조치이력 수정,삭제 제한
- resolved: #243

[#243] 조치이력 수정,삭제 제한 

---

src/main/webapp/WEB-INF/views/defect/defect.jsp
src/main/webapp/resources/defect/css/defect.css
src/main/webapp/resources/defect/js/defect.js
src/main/webapp/resources/defect/js/list.js

- 첨부파일 바운더리 재지정
- 파일 저장 시 삭제 파일 제거 안되는 문제 발생
- resolved: #234

[#234] 결함 저장 오류 개선

---

src/main/webapp/resources/common/js/common.js
src/main/webapp/resources/member/css/teamMemberRegister.css
src/main/webapp/resources/member/js/teamMemberRegister.js
src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
src/main/webapp/resources/wbs/js/wbsInfo.js

- 인력등록 팝업페이지 오류 수정 
-  특정 페이지에서 멤버가 추가가 안되는 문제 해결
-  wbs 페이지에서 다른 인력 팝업 페이지가 나오는 문제 해결
- resolved: #246

[#246] 인력등록 팝업페이지 오류 수정 

---

pom.xml
src/main/java/com/kcc/pms/domain/common/util/ExcelGenerator.java
src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
src/main/java/com/kcc/pms/domain/risk/model/excel/ExcelFileDetailDto.java
src/main/java/com/kcc/pms/domain/risk/model/excel/ExcelHistoryDto.java
src/main/java/com/kcc/pms/domain/risk/model/excel/ExcelRiskDto.java
src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
src/main/resources/data.sql
src/main/resources/mapper/task/RiskMapper.xml
src/main/webapp/resources/danger/js/danger.js

- 위험 관리 대장 액셀 다운로드 
- resolved: #229

[#229] 위험 관리 대장 액셀 다운로드 

---

src/main/java/com/kcc/pms/domain/common/util/IssueExcelGenerator.java
src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
src/main/java/com/kcc/pms/domain/risk/model/dto/CriteriaRisk.java
src/main/java/com/kcc/pms/domain/risk/model/dto/RiskDto.java
src/main/java/com/kcc/pms/domain/risk/model/excel/ExcelRiskDto.java
src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
src/main/java/com/kcc/pms/domain/task/issue/controller/IssueController.java
src/main/resources/data.sql
src/main/resources/mapper/task/RiskMapper.xml
src/main/webapp/WEB-INF/views/issue/info.jsp
src/main/webapp/WEB-INF/views/issue/list.jsp
src/main/webapp/resources/danger/js/danger.js
src/main/webapp/resources/danger/js/info.js
src/main/webapp/resources/issue/js/info.js
src/main/webapp/resources/issue/js/list.js

[#256] 이슈 기능 완성 

---

src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
src/main/java/com/kcc/pms/domain/member/model/dto/MemberTeamUpdateRequest.java
src/main/java/com/kcc/pms/domain/member/service/MemberService.java
src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
src/main/java/com/kcc/pms/domain/team/model/dto/MemberAddRequestDto.java
src/main/java/com/kcc/pms/domain/team/service/TeamService.java
src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/resources/member/js/memberRegisterGrid.js

- 조직도에서 멤버 추가 시 프로젝트 권환 디폴트 설정
- 인력 추가 로직 리팩토링 (개별 쿼리 -> 멀티 쿼리)
- resolved: #260

[#260] 투입인력팝업페이지 보완

---

src/main/java/com/kcc/pms/domain/member/service/MemberService.java
src/main/java/com/kcc/pms/domain/output/service/OutputServiceImpl.java
src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
src/main/resources/data.sql
src/main/resources/mapper/OutputMapper.xml
src/main/resources/mapper/TestMapper.xml
src/main/webapp/resources/common/js/common.js
src/main/webapp/resources/test/js/test.js

- 테스트 결함 산출물 오류 수정
- resolved: #263

[#263] 테스트 결함 산출물 오류 수정

---

src/main/java/com/kcc/pms/domain/common/util/ExcelGenerator.java
src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
src/main/java/com/kcc/pms/domain/member/model/dto/GroupMembersResponseDto.java
src/main/java/com/kcc/pms/domain/member/model/dto/MemberResponseDto.java
src/main/java/com/kcc/pms/domain/member/service/MemberService.java
src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
src/main/resources/data.sql
src/main/resources/mapper/FeatureMapper.xml
src/main/webapp/WEB-INF/views/danger/danger_list.jsp
src/main/webapp/WEB-INF/views/feature/list.jsp
src/main/webapp/WEB-INF/views/issue/list.jsp
src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/WEB-INF/views/member/memberRegister.jsp
src/main/webapp/resources/feature/js/list.js
src/main/webapp/resources/member/css/list.css
src/main/webapp/resources/member/css/memberRegister.css
src/main/webapp/resources/member/js/list.js
src/main/webapp/resources/member/js/memberRegister.js
src/main/webapp/resources/member/js/memberRegisterGrid.js
src/main/webapp/resources/member/js/teamMemberRegisterGrid.js

- refactor: 더미수정
- resolved: #266

[#266] refactor: 더미수정

---

src/main/resources/mapper/FeatureMapper.xml
src/main/resources/mapper/MemberMapper.xml
src/main/resources/mapper/task/DefectMapper.xml
src/main/resources/mapper/task/RiskMapper.xml
src/main/webapp/resources/feature/js/list.js

[fix] to_date 개선

---

src/main/resources/mapper/ProjectMapper.xml
src/main/resources/mapper/TestMapper.xml
src/main/resources/mapper/WbsMapper.xml

- TO_DATE 오류 해결
- resolved: #275

[#275] to_date_fix

---

src/main/resources/mapper/FeatureMapper.xml
src/main/resources/mapper/MemberMapper.xml
src/main/resources/mapper/ProjectMapper.xml
src/main/resources/mapper/TestMapper.xml
src/main/resources/mapper/WbsMapper.xml
src/main/resources/mapper/task/DefectMapper.xml
src/main/resources/mapper/task/RiskMapper.xml

운영환경 코드 적용
